"""Persist five LLM slots: 3 chat + embed + rerank."""

from __future__ import annotations

import json
import logging
import os
import tempfile
from pathlib import Path
from typing import Any

from gateway.app.config import Settings, get_settings
from gateway.app.schemas.llm import (
    LlmAgentBinding,
    LlmModelInfo,
    LlmSettingsResponse,
    LlmSettingsUpdate,
    LlmSlotStatus,
    LlmSlotUpdate,
)

logger = logging.getLogger("researchos.gateway.llm")

# Fixed slots — no vendor sprawl
SLOTS: list[tuple[str, str, str, str, str]] = [
    # id, label, kind, default_model, default_base_url
    ("chat_a", "对话模型 A", "chat", "gpt-4o-mini", "https://api.openai.com/v1"),
    ("chat_b", "对话模型 B", "chat", "gpt-4o-mini", "https://api.openai.com/v1"),
    ("chat_c", "对话模型 C", "chat", "gpt-4o-mini", "https://api.openai.com/v1"),
    ("embed", "Embedding", "embed", "text-embedding-3-small", "https://api.openai.com/v1"),
    ("rerank", "重排序", "rerank", "jina-reranker-v2-base-multilingual", "https://api.jina.ai/v1"),
]

_SLOT_META = {
    sid: {
        "label": label,
        "kind": kind,
        "default_model": model,
        "default_base_url": base,
    }
    for sid, label, kind, model, base in SLOTS
}

CHAT_SLOT_IDS = {"chat_a", "chat_b", "chat_c"}
VALID_SLOT_IDS = set(_SLOT_META)


def _settings_path(settings: Settings | None = None) -> Path:
    settings = settings or get_settings()
    override = os.getenv("LLM_SETTINGS_PATH", "").strip()
    if override:
        return Path(override).expanduser()
    base = Path(settings.plc_work_dir or tempfile.gettempdir()) / "researchos_llm"
    base.mkdir(parents=True, exist_ok=True)
    return base / "settings.json"


def _keys_path(settings: Settings | None = None) -> Path:
    return _settings_path(settings).with_name("slot_keys.json")


def _slots_path(settings: Settings | None = None) -> Path:
    return _settings_path(settings).with_name("slot_configs.json")


def _load_json(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return {}


def _mask(value: str) -> str:
    v = value.strip()
    if len(v) <= 8:
        return "****"
    return f"{v[:4]}…{v[-4:]}"


def _migrate_legacy_keys(raw_keys: dict[str, Any]) -> dict[str, str]:
    """Accept old provider_keys.json shape if present."""
    legacy_path = _settings_path().with_name("provider_keys.json")
    legacy = _load_json(legacy_path) if not raw_keys else {}
    merged = {**legacy, **raw_keys}
    out: dict[str, str] = {}
    # map old vendor keys onto chat_a if slots empty
    vendor_key = (
        str(merged.get("openai") or merged.get("deepseek") or merged.get("dashscope") or "")
    ).strip()
    for sid in VALID_SLOT_IDS:
        if sid in merged and str(merged[sid]).strip():
            out[sid] = str(merged[sid]).strip()
    if vendor_key and "chat_a" not in out:
        out["chat_a"] = vendor_key
    return out


def _load_slot_configs() -> dict[str, dict[str, str]]:
    raw = _load_json(_slots_path())
    legacy = _load_json(_settings_path().with_name("provider_configs.json"))
    out: dict[str, dict[str, str]] = {}
    for sid, meta in _SLOT_META.items():
        row = raw.get(sid) if isinstance(raw.get(sid), dict) else {}
        if not row and sid == "chat_a" and isinstance(legacy.get("openai"), dict):
            row = legacy["openai"]
        out[sid] = {
            "model": str(row.get("model") or meta["default_model"]).strip(),
            "base_url": str(
                row.get("base_url") if row.get("base_url") is not None else meta["default_base_url"]
            ).strip(),
        }
    return out


def _write_runtime_artifacts(keys: dict[str, str], configs: dict[str, dict[str, str]]) -> None:
    base = _slots_path().parent
    base.mkdir(parents=True, exist_ok=True)

    env_lines: list[str] = []
    for sid, key in keys.items():
        env_name = f"ROS_LLM_{sid.upper()}_API_KEY"
        env_lines.append(f"{env_name}={key}")
        os.environ[env_name] = key
    for sid, cfg in configs.items():
        if cfg.get("base_url"):
            env_lines.append(f"ROS_LLM_{sid.upper()}_BASE_URL={cfg['base_url']}")
            os.environ[f"ROS_LLM_{sid.upper()}_BASE_URL"] = cfg["base_url"]
        if cfg.get("model"):
            env_lines.append(f"ROS_LLM_{sid.upper()}_MODEL={cfg['model']}")
            os.environ[f"ROS_LLM_{sid.upper()}_MODEL"] = cfg["model"]

    (base / "provider_keys.env").write_text(
        "\n".join(env_lines) + ("\n" if env_lines else ""),
        encoding="utf-8",
    )

    yaml_lines = [
        "# Generated by ResearchOS — 3 chat + embed + rerank",
        "model_list:",
    ]
    for sid, cfg in configs.items():
        meta = _SLOT_META[sid]
        model = cfg.get("model") or meta["default_model"]
        kind = meta["kind"]
        if kind == "chat":
            litellm_model = model if "/" in model else f"openai/{model}"
        elif kind == "embed":
            litellm_model = model if "/" in model else f"openai/{model}"
        else:
            # rerank — prefer openai-compatible or jina/
            litellm_model = model if "/" in model else f"jina_ai/{model}"
        yaml_lines.append(f"  - model_name: {sid}")
        yaml_lines.append("    litellm_params:")
        yaml_lines.append(f"      model: {litellm_model}")
        yaml_lines.append(f"      api_key: os.environ/ROS_LLM_{sid.upper()}_API_KEY")
        if cfg.get("base_url"):
            yaml_lines.append(f"      api_base: {cfg['base_url']}")
        # aliases for legacy agent names
        if sid == "chat_a":
            for alias in ("default", "planner", "strong"):
                yaml_lines.append(f"  - model_name: {alias}")
                yaml_lines.append("    litellm_params:")
                yaml_lines.append(f"      model: {litellm_model}")
                yaml_lines.append("      api_key: os.environ/ROS_LLM_CHAT_A_API_KEY")
                if cfg.get("base_url"):
                    yaml_lines.append(f"      api_base: {cfg['base_url']}")
        if sid == "chat_b":
            for alias in ("researcher", "plc"):
                yaml_lines.append(f"  - model_name: {alias}")
                yaml_lines.append("    litellm_params:")
                yaml_lines.append(f"      model: {litellm_model}")
                yaml_lines.append("      api_key: os.environ/ROS_LLM_CHAT_B_API_KEY")
                if cfg.get("base_url"):
                    yaml_lines.append(f"      api_base: {cfg['base_url']}")
        if sid == "chat_c":
            yaml_lines.append("  - model_name: writer")
            yaml_lines.append("    litellm_params:")
            yaml_lines.append(f"      model: {litellm_model}")
            yaml_lines.append("      api_key: os.environ/ROS_LLM_CHAT_C_API_KEY")
            if cfg.get("base_url"):
                yaml_lines.append(f"      api_base: {cfg['base_url']}")

    (base / "litellm_providers.generated.yaml").write_text("\n".join(yaml_lines) + "\n", encoding="utf-8")
    (base / "provider_runtime.json").write_text(
        json.dumps({"slots": configs, "keys": list(keys.keys())}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def _slot_status() -> list[LlmSlotStatus]:
    keys = _migrate_legacy_keys(_load_json(_keys_path()))
    configs = _load_slot_configs()
    out: list[LlmSlotStatus] = []
    for sid, meta in _SLOT_META.items():
        key = keys.get(sid, "")
        env_key = (os.getenv(f"ROS_LLM_{sid.upper()}_API_KEY") or "").strip()
        configured = bool(key or env_key)
        hint = None
        if env_key:
            hint = f"env:{_mask(env_key)}"
        elif key:
            hint = f"ui:{_mask(key)}"
        cfg = configs[sid]
        out.append(
            LlmSlotStatus(
                id=sid,
                label=meta["label"],
                kind=meta["kind"],  # type: ignore[arg-type]
                configured=configured,
                hint=hint,
                model=cfg["model"],
                base_url=cfg["base_url"],
                default_model=meta["default_model"],
                default_base_url=meta["default_base_url"],
            )
        )
    return out


def _catalog() -> list[LlmModelInfo]:
    return [
        LlmModelInfo(
            id=sid,
            label=meta["label"],
            provider="slot",
            kind=meta["kind"],
            requires_key=sid,
        )
        for sid, meta in _SLOT_META.items()
    ]


def _normalize_binding(value: str, *, allowed: set[str], fallback: str) -> str:
    v = (value or "").strip()
    legacy = {
        "default": "chat_a",
        "planner": "chat_a",
        "strong": "chat_a",
        "researcher": "chat_b",
        "plc": "chat_b",
        "writer": "chat_c",
        "openai-gpt-4o-mini": "chat_a",
        "openai-gpt-4o": "chat_a",
        "openai-custom": "chat_a",
        "anthropic-claude-sonnet": "chat_b",
        "deepseek-chat": "chat_b",
        "qwen-plus": "chat_c",
        "qwen-max": "chat_c",
        "gemini-2.0-flash": "chat_b",
        "local": "chat_c",
        "ollama-qwen": "chat_c",
        "ollama-custom": "chat_c",
    }
    if v in legacy:
        v = legacy[v]
    if v not in allowed:
        return fallback
    return v


def load_agent_bindings() -> LlmAgentBinding:
    data = _load_json(_settings_path())
    agents = data.get("agents") or {}
    chat_allowed = CHAT_SLOT_IDS
    return LlmAgentBinding(
        research=_normalize_binding(str(agents.get("research") or "chat_a"), allowed=chat_allowed, fallback="chat_a"),
        planner=_normalize_binding(str(agents.get("planner") or "chat_a"), allowed=chat_allowed, fallback="chat_a"),
        researcher=_normalize_binding(
            str(agents.get("researcher") or "chat_b"), allowed=chat_allowed, fallback="chat_b"
        ),
        writer=_normalize_binding(str(agents.get("writer") or "chat_c"), allowed=chat_allowed, fallback="chat_c"),
        plc=_normalize_binding(str(agents.get("plc") or "chat_b"), allowed=chat_allowed, fallback="chat_b"),
        embed=_normalize_binding(str(agents.get("embed") or "embed"), allowed={"embed"}, fallback="embed"),
        rerank=_normalize_binding(str(agents.get("rerank") or "rerank"), allowed={"rerank"}, fallback="rerank"),
    )


def get_llm_settings() -> LlmSettingsResponse:
    settings = get_settings()
    bindings = load_agent_bindings()
    slots = _slot_status()
    return LlmSettingsResponse(
        catalog=_catalog(),
        agents=bindings,
        slots=slots,
        providers=slots,
        litellm_base_url=settings.litellm_base_url,
        default_model="chat_a",
        notes=[
            "仅 5 个槽位：对话 A/B/C、Embedding、重排序。",
            "每个槽位配置 API Key、Model、Base URL。",
            "保存后生成 litellm_providers.generated.yaml，需重启 LiteLLM。",
        ],
    )


def update_llm_settings(body: LlmSettingsUpdate) -> LlmSettingsResponse:
    path = _settings_path()
    data = _load_json(path)
    configs = _load_slot_configs()
    keys = _migrate_legacy_keys(_load_json(_keys_path()))

    updates = body.slots or body.providers
    if body.provider_keys:
        for sid, key in body.provider_keys.items():
            if sid not in VALID_SLOT_IDS:
                # ignore unknown legacy vendor ids quietly for chat_a map
                if sid in {"openai", "anthropic", "deepseek", "dashscope", "gemini"}:
                    keys["chat_a"] = (key or "").strip() or keys.get("chat_a", "")
                    if not keys["chat_a"]:
                        keys.pop("chat_a", None)
                continue
            key = (key or "").strip()
            if not key:
                keys.pop(sid, None)
            else:
                keys[sid] = key

    if updates:
        for sid, upd in updates.items():
            if sid not in VALID_SLOT_IDS:
                raise ValueError(f"Unknown slot: {sid}")
            if not isinstance(upd, LlmSlotUpdate):
                upd = LlmSlotUpdate.model_validate(upd)
            row = dict(configs.get(sid) or {})
            if upd.model is not None:
                row["model"] = upd.model.strip() or _SLOT_META[sid]["default_model"]
            if upd.base_url is not None:
                row["base_url"] = upd.base_url.strip()
            configs[sid] = {
                "model": row.get("model") or _SLOT_META[sid]["default_model"],
                "base_url": row.get("base_url", _SLOT_META[sid]["default_base_url"]),
            }
            if upd.api_key is not None:
                key = upd.api_key.strip()
                if not key:
                    keys.pop(sid, None)
                else:
                    keys[sid] = key

    if body.agents is not None:
        catalog_ids = {m.id for m in _catalog()}
        agents = body.agents.model_dump()
        for role, mid in agents.items():
            mid = _normalize_binding(
                mid,
                allowed=catalog_ids,
                fallback="chat_a" if role != "embed" and role != "rerank" else role,
            )
            agents[role] = mid
            if mid not in catalog_ids:
                raise ValueError(f"Unknown model id for {role}: {mid}")
        data["agents"] = agents
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")

    keys_path = _keys_path()
    keys_path.parent.mkdir(parents=True, exist_ok=True)
    keys_path.write_text(json.dumps(keys, ensure_ascii=False, indent=2), encoding="utf-8")
    _slots_path().write_text(json.dumps(configs, ensure_ascii=False, indent=2), encoding="utf-8")
    _write_runtime_artifacts(keys, configs)
    logger.info("LLM slots updated path=%s", _slots_path())
    return get_llm_settings()


def resolve_model_profile(explicit: str | None = None) -> str:
    if explicit and explicit.strip() and explicit.strip() not in {"default", ""}:
        normalized = _normalize_binding(
            explicit.strip(),
            allowed=VALID_SLOT_IDS | CHAT_SLOT_IDS,
            fallback="chat_a",
        )
        return normalized
    return load_agent_bindings().research
