"""Plot core: deterministic code generation + subprocess render (code is the artifact).

Design (ADR-0012): 代码是产物、图是渲染结果;脚本随图可复现;默认只读执行沙箱、无网络。
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import Any

PLOT_KINDS = {"bar", "line", "scatter"}


def _build_code(path: str, x: str, y: str, kind: str, out_png: str, title: str = "") -> str:
    kind = kind if kind in PLOT_KINDS else "bar"
    if kind == "scatter":
        draw = f"ax.scatter(df[{x!r}], df[{y!r}])"
    elif kind == "line":
        draw = f"ax.plot(df[{x!r}], df[{y!r}])"
    else:
        draw = f"ax.bar(df[{x!r}].astype(str), df[{y!r}])"

    return (
        "# Generated by ResearchOS tools.plot (reproducible artifact)\n"
        "import matplotlib\n"
        'matplotlib.use("Agg")\n'
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n\n"
        f"df = pd.read_csv({path!r})\n"
        "fig, ax = plt.subplots()\n"
        f"{draw}\n"
        f'ax.set_xlabel({x!r})\n'
        f'ax.set_ylabel({y!r})\n'
        f'ax.set_title({title!r})\n'
        "fig.tight_layout()\n"
        f'fig.savefig({out_png!r}, dpi=300)\n'
    )


def read_columns(path: str) -> dict[str, Any]:
    import pandas as pd

    df = _read_table(path)
    return {
        "path": str(path),
        "columns": [str(c) for c in df.columns],
        "rows": int(len(df)),
    }


def _read_table(path: str):
    import pandas as pd

    p = Path(path)
    suffix = p.suffix.lower()
    if suffix in (".csv", ".tsv"):
        return pd.read_csv(p, sep=None, engine="python")
    if suffix in (".xlsx", ".xls"):
        return pd.read_excel(p)
    raise ValueError(f"unsupported table format: {suffix}")


def render(
    path: str,
    x: str,
    y: str,
    *,
    kind: str = "bar",
    title: str = "",
    out_dir: str | None = None,
) -> dict[str, Any]:
    import pandas as pd

    df = _read_table(path)
    if x not in df.columns:
        raise ValueError(f"column not found: {x}")
    if y not in df.columns:
        raise ValueError(f"column not found: {y}")

    out = Path(out_dir or Path(path).parent)
    out.mkdir(parents=True, exist_ok=True)
    stem = Path(path).stem or "plot"
    out_png = out / f"{stem}_{kind}.png"
    script = out / f"{stem}_{kind}.py"

    code = _build_code(str(Path(path).resolve()), x, y, kind, str(out_png.resolve()), title)
    script.write_text(code, encoding="utf-8")

    proc = subprocess.run(
        [sys.executable, str(script)],
        capture_output=True,
        text=True,
        timeout=120,
    )
    ok = proc.returncode == 0 and out_png.exists()
    return {
        "ok": ok,
        "image": str(out_png) if ok else None,
        "script": str(script),
        "columns": [str(c) for c in df.columns],
        "rows": int(len(df)),
        "kind": kind,
        "returncode": proc.returncode,
        "stderr": (proc.stderr or "")[-1000:],
    }


def plot_file(
    path: str,
    x: str,
    y: str,
    *,
    kind: str = "bar",
    title: str = "",
    out_dir: str | None = None,
) -> dict[str, Any]:
    return render(path, x, y, kind=kind, title=title, out_dir=out_dir)
